AttachSpec("~/github/CHIMP/CHIMP.spec");
AttachSpec("~/github/Gm-Reduce/spec");
SetVerbose("GmReduce",true);

QQ := Rationals();
gens := GetModularCurveGenerators("9.108.4.1");
N := Characteristic(BaseRing(Parent(gens[1])));
rec := CreateModularCurveRec(N,gens);
bool, polys, fs := FindCanonicalModel(rec,20);
S := Parent(polys[1]);
S := ChangeRing(S,QQ);
C := Curve(Proj(S),polys);
print C;
Ps := PointSearch(C,20);
K := RationalsAsNumberField();
C := ChangeRing(C,K);
Ps := [C!Eltseq(el) : el in Ps];
Ps := [Place(el) : el in Ps];
KC<x,y,z> := FunctionField(C);
time small3 := SmallFunctions(Ps,3);
